FROM bitnami/tomcat:latest
FROM ubuntu:latest

RUN apt-get update && apt-get -y install unzip wget
RUN wget -q https://sourceforge.net/projects/geoserver/files/GeoServer/2.16.0/geoserver-2.16.0-war.zip/download -O tmp/geoserver.zip
RUN unzip -q tmp/geoserver.zip -d tmp
RUN mv tmp/geoserver.war opt/tomcat/webapps/geoserver.war

CMD opt/tomcat/bin/deploy-and-run.sh